sudo: required
services:
  - docker

before-install:
  - ls -la
  - docker pull node:alpine
  - docker build -t myapp .

script:
  - ls -la
  - docker pull node:alpine
  - docker build -t myapp .
  - docker run myapp npm run test -- --coverage
