language: generic 
sudo: required
services:
  - docker

before-install:
  - ls -la
  - docker build -t briandavidsen/docker-react -f ./Dockerfile.dev .

script:
  - docker run briandavidsen/docker-react npm run test -- --coverage
