sudo: required
services:
  - docker

before_script: 
  - ls
  - docker build -t myapp -f Dockerfile.dev .

script:
  - docker run -e CI=true myapp npm run test

deploy:
  provider: elasticbeanstak
  region: "us-east-1"
  app: "myReactApp"
  env: "Myreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-167305595830"
  bucket_path: "myReactApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  

