sudo: required
services:
  - docker

before-install:
  - docker build -t briandavidsen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true briandavidsen/docker-react npm run test -- --coverage
